[gspread]
type = "service_account"
project_id = "appointment2026"
private_key_id = "a63d42d03d30b864ec123377bedb23b8598dee"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDbT8YvWZUE... (เอาคีย์ยาวๆ ทั้งหมดมาวางต่อตรงนี้ยาวๆ เป็นบรรทัดเดียวจบเลยครับ) \\n-----END PRIVATE KEY-----"
client_email = "appointment-bot@appointment2026.iam.gserviceaccount.com"
client_id = "108634656719463519344"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/appointment-bot%40appointment2026.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
